---
engines:
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- spec/**/*
- spec/**/*
- .codeclimate.yml 
